// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egsiycjueeslsjzjkwxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnc2l5Y2p1ZWVzbHNqemprd3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODM5NTQsImV4cCI6MjA3MTY1OTk1NH0.-LeOuSB3TaBcoZtZZM14A2wVCIsHKRYGZ-0Ar7a8nso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});